/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherSubRouteImport } from './routes/teacher.$sub'
import { Route as RamadanSubRouteImport } from './routes/ramadan.$sub'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as NewbornSubRouteImport } from './routes/newborn.$sub'
import { Route as MotherSubRouteImport } from './routes/mother.$sub'
import { Route as GraduationSubRouteImport } from './routes/graduation.$sub'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as MotherQuranBoxesItemRouteImport } from './routes/mother.quran-boxes.$item'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSubRoute = TeacherSubRouteImport.update({
  id: '/teacher/$sub',
  path: '/teacher/$sub',
  getParentRoute: () => rootRouteImport,
} as any)
const RamadanSubRoute = RamadanSubRouteImport.update({
  id: '/ramadan/$sub',
  path: '/ramadan/$sub',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NewbornSubRoute = NewbornSubRouteImport.update({
  id: '/newborn/$sub',
  path: '/newborn/$sub',
  getParentRoute: () => rootRouteImport,
} as any)
const MotherSubRoute = MotherSubRouteImport.update({
  id: '/mother/$sub',
  path: '/mother/$sub',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduationSubRoute = GraduationSubRouteImport.update({
  id: '/graduation/$sub',
  path: '/graduation/$sub',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MotherQuranBoxesItemRoute = MotherQuranBoxesItemRouteImport.update({
  id: '/mother/quran-boxes/$item',
  path: '/mother/quran-boxes/$item',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/category/$slug': typeof CategorySlugRoute
  '/graduation/$sub': typeof GraduationSubRoute
  '/mother/$sub': typeof MotherSubRoute
  '/newborn/$sub': typeof NewbornSubRoute
  '/product/$id': typeof ProductIdRoute
  '/ramadan/$sub': typeof RamadanSubRoute
  '/teacher/$sub': typeof TeacherSubRoute
  '/mother/quran-boxes/$item': typeof MotherQuranBoxesItemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/category/$slug': typeof CategorySlugRoute
  '/graduation/$sub': typeof GraduationSubRoute
  '/mother/$sub': typeof MotherSubRoute
  '/newborn/$sub': typeof NewbornSubRoute
  '/product/$id': typeof ProductIdRoute
  '/ramadan/$sub': typeof RamadanSubRoute
  '/teacher/$sub': typeof TeacherSubRoute
  '/mother/quran-boxes/$item': typeof MotherQuranBoxesItemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/category/$slug': typeof CategorySlugRoute
  '/graduation/$sub': typeof GraduationSubRoute
  '/mother/$sub': typeof MotherSubRoute
  '/newborn/$sub': typeof NewbornSubRoute
  '/product/$id': typeof ProductIdRoute
  '/ramadan/$sub': typeof RamadanSubRoute
  '/teacher/$sub': typeof TeacherSubRoute
  '/mother/quran-boxes/$item': typeof MotherQuranBoxesItemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/category/$slug'
    | '/graduation/$sub'
    | '/mother/$sub'
    | '/newborn/$sub'
    | '/product/$id'
    | '/ramadan/$sub'
    | '/teacher/$sub'
    | '/mother/quran-boxes/$item'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/category/$slug'
    | '/graduation/$sub'
    | '/mother/$sub'
    | '/newborn/$sub'
    | '/product/$id'
    | '/ramadan/$sub'
    | '/teacher/$sub'
    | '/mother/quran-boxes/$item'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/category/$slug'
    | '/graduation/$sub'
    | '/mother/$sub'
    | '/newborn/$sub'
    | '/product/$id'
    | '/ramadan/$sub'
    | '/teacher/$sub'
    | '/mother/quran-boxes/$item'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CategorySlugRoute: typeof CategorySlugRoute
  GraduationSubRoute: typeof GraduationSubRoute
  MotherSubRoute: typeof MotherSubRoute
  NewbornSubRoute: typeof NewbornSubRoute
  ProductIdRoute: typeof ProductIdRoute
  RamadanSubRoute: typeof RamadanSubRoute
  TeacherSubRoute: typeof TeacherSubRoute
  MotherQuranBoxesItemRoute: typeof MotherQuranBoxesItemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/$sub': {
      id: '/teacher/$sub'
      path: '/teacher/$sub'
      fullPath: '/teacher/$sub'
      preLoaderRoute: typeof TeacherSubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ramadan/$sub': {
      id: '/ramadan/$sub'
      path: '/ramadan/$sub'
      fullPath: '/ramadan/$sub'
      preLoaderRoute: typeof RamadanSubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newborn/$sub': {
      id: '/newborn/$sub'
      path: '/newborn/$sub'
      fullPath: '/newborn/$sub'
      preLoaderRoute: typeof NewbornSubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mother/$sub': {
      id: '/mother/$sub'
      path: '/mother/$sub'
      fullPath: '/mother/$sub'
      preLoaderRoute: typeof MotherSubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduation/$sub': {
      id: '/graduation/$sub'
      path: '/graduation/$sub'
      fullPath: '/graduation/$sub'
      preLoaderRoute: typeof GraduationSubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mother/quran-boxes/$item': {
      id: '/mother/quran-boxes/$item'
      path: '/mother/quran-boxes/$item'
      fullPath: '/mother/quran-boxes/$item'
      preLoaderRoute: typeof MotherQuranBoxesItemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CategorySlugRoute: CategorySlugRoute,
  GraduationSubRoute: GraduationSubRoute,
  MotherSubRoute: MotherSubRoute,
  NewbornSubRoute: NewbornSubRoute,
  ProductIdRoute: ProductIdRoute,
  RamadanSubRoute: RamadanSubRoute,
  TeacherSubRoute: TeacherSubRoute,
  MotherQuranBoxesItemRoute: MotherQuranBoxesItemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
